-- Create books table
CREATE TABLE IF NOT EXISTS books (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  genre TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for efficient searching
CREATE INDEX IF NOT EXISTS idx_books_title_lower ON books(LOWER(title));
CREATE INDEX IF NOT EXISTS idx_books_author_lower ON books(LOWER(author));
CREATE INDEX IF NOT EXISTS idx_books_genre ON books(genre);
CREATE INDEX IF NOT EXISTS idx_books_title_author ON books(LOWER(title), LOWER(author));

-- Insert books from CSV
INSERT INTO books (title, author, genre) VALUES
('The Spanish Love Deception', 'Elena Armas', 'Romance'),
('The Love Hypothesis', 'Ali Hazelwood', 'Romance'),
('Beach Read', 'Emily Henry', 'Romance'),
('Book Lovers', 'Emily Henry', 'Romance'),
('People We Meet on Vacation', 'Emily Henry', 'Romance'),
('Happy Place', 'Emily Henry', 'Romance'),
('The Seven Husbands of Evelyn Hugo', 'Taylor Jenkins Reid', 'Romance'),
('Daisy Jones & The Six', 'Taylor Jenkins Reid', 'Romance'),
('Malibu Rising', 'Taylor Jenkins Reid', 'Romance'),
('Carrie Soto Is Back', 'Taylor Jenkins Reid', 'Romance'),
('The Hating Game', 'Sally Thorne', 'Romance'),
('Red White & Royal Blue', 'Casey McQuiston', 'Romance'),
('One Last Stop', 'Casey McQuiston', 'Romance'),
('The Kiss Quotient', 'Helen Hoang', 'Romance'),
('The Bride Test', 'Helen Hoang', 'Romance'),
('The Heart Principle', 'Helen Hoang', 'Romance'),
('From Blood and Ash', 'Jennifer L. Armentrout', 'Romance'),
('A Kingdom of Flesh and Fire', 'Jennifer L. Armentrout', 'Romance'),
('The Crown of Gilded Bones', 'Jennifer L. Armentrout', 'Romance'),
('Things We Never Got Over', 'Lucy Score', 'Romance'),
('Things We Hide from the Light', 'Lucy Score', 'Romance'),
('The Unhoneymooners', 'Christina Lauren', 'Romance'),
('The Soulmate Equation', 'Christina Lauren', 'Romance'),
('The Proposal', 'Jasmine Guillory', 'Romance'),
('The Wedding Date', 'Jasmine Guillory', 'Romance'),
('The Time Traveler''s Wife', 'Audrey Niffenegger', 'Romance'),
('Me Before You', 'Jojo Moyes', 'Romance'),
('After You', 'Jojo Moyes', 'Romance'),
('The Flatshare', 'Beth O''Leary', 'Romance'),
('The Switch', 'Beth O''Leary', 'Romance'),
('Haunting Adeline', 'H.D. Carlton', 'Dark Romance'),
('Hunting Adeline', 'H.D. Carlton', 'Dark Romance'),
('Credence', 'Penelope Douglas', 'Dark Romance'),
('Birthday Girl', 'Penelope Douglas', 'Dark Romance'),
('Punk 57', 'Penelope Douglas', 'Dark Romance'),
('Corrupt', 'Penelope Douglas', 'Dark Romance'),
('Den of Vipers', 'K.A. Knight', 'Dark Romance'),
('Butcher & Blackbird', 'Brynne Weaver', 'Dark Romance'),
('Beneath the Stands', 'Penelope Douglas', 'Dark Romance'),
('Still Beating', 'Jennifer Hartmann', 'Dark Romance'),
('A Court of Thorns and Roses', 'Sarah J. Maas', 'Fantasy Romance'),
('A Court of Mist and Fury', 'Sarah J. Maas', 'Fantasy Romance'),
('A Court of Wings and Ruin', 'Sarah J. Maas', 'Fantasy Romance'),
('A Court of Frost and Starlight', 'Sarah J. Maas', 'Fantasy Romance'),
('A Court of Silver Flames', 'Sarah J. Maas', 'Fantasy Romance'),
('Throne of Glass', 'Sarah J. Maas', 'Fantasy Romance'),
('Crown of Midnight', 'Sarah J. Maas', 'Fantasy Romance'),
('Heir of Fire', 'Sarah J. Maas', 'Fantasy Romance'),
('Queen of Shadows', 'Sarah J. Maas', 'Fantasy Romance'),
('Empire of Storms', 'Sarah J. Maas', 'Fantasy Romance'),
('Tower of Dawn', 'Sarah J. Maas', 'Fantasy Romance'),
('Kingdom of Ash', 'Sarah J. Maas', 'Fantasy Romance'),
('Crescent City: House of Earth and Blood', 'Sarah J. Maas', 'Fantasy Romance'),
('Crescent City: House of Sky and Breath', 'Sarah J. Maas', 'Fantasy Romance'),
('Crescent City: House of Flame and Shadow', 'Sarah J. Maas', 'Fantasy Romance'),
('Fourth Wing', 'Rebecca Yarros', 'Fantasy Romance'),
('Iron Flame', 'Rebecca Yarros', 'Fantasy Romance'),
('Onyx Storm', 'Rebecca Yarros', 'Fantasy Romance'),
('Powerless', 'Lauren Roberts', 'Fantasy Romance'),
('Reckless', 'Lauren Roberts', 'Fantasy Romance'),
('Divine Rivals', 'Rebecca Ross', 'Fantasy Romance'),
('Ruthless Vows', 'Rebecca Ross', 'Fantasy Romance'),
('The Cruel Prince', 'Holly Black', 'Fantasy Romance'),
('The Wicked King', 'Holly Black', 'Fantasy Romance'),
('The Queen of Nothing', 'Holly Black', 'Fantasy Romance'),
('Shadow and Bone', 'Leigh Bardugo', 'Fantasy Romance'),
('Siege and Storm', 'Leigh Bardugo', 'Fantasy Romance'),
('Ruin and Rising', 'Leigh Bardugo', 'Fantasy Romance'),
('Six of Crows', 'Leigh Bardugo', 'Fantasy Romance'),
('Crooked Kingdom', 'Leigh Bardugo', 'Fantasy Romance'),
('King of Battle and Blood', 'Scarlett St. Clair', 'Fantasy Romance'),
('King of Wrath', 'Ana Huang', 'Fantasy Romance'),
('King of Pride', 'Ana Huang', 'Fantasy Romance'),
('King of Greed', 'Ana Huang', 'Fantasy Romance'),
('King of Sloth', 'Ana Huang', 'Fantasy Romance'),
('Twisted Love', 'Ana Huang', 'Fantasy Romance'),
('Twisted Games', 'Ana Huang', 'Fantasy Romance'),
('Twisted Hate', 'Ana Huang', 'Fantasy Romance'),
('Twisted Lies', 'Ana Huang', 'Fantasy Romance'),
('A Shadow in the Ember', 'Jennifer L. Armentrout', 'Fantasy Romance'),
('The Summer I Turned Pretty', 'Jenny Han', 'Contemporary Romance'),
('It''s Not Summer Without You', 'Jenny Han', 'Contemporary Romance'),
('We''ll Always Have Summer', 'Jenny Han', 'Contemporary Romance'),
('To All the Boys I''ve Loved Before', 'Jenny Han', 'Contemporary Romance'),
('P.S. I Still Love You', 'Jenny Han', 'Contemporary Romance'),
('Always and Forever Lara Jean', 'Jenny Han', 'Contemporary Romance'),
('Icebreaker', 'Hannah Grace', 'Contemporary Romance'),
('Wildfire', 'Hannah Grace', 'Contemporary Romance'),
('Daydream', 'Hannah Grace', 'Contemporary Romance'),
('The Deal', 'Elle Kennedy', 'Contemporary Romance'),
('The Mistake', 'Elle Kennedy', 'Contemporary Romance'),
('The Score', 'Elle Kennedy', 'Contemporary Romance'),
('The Goal', 'Elle Kennedy', 'Contemporary Romance'),
('The Legacy', 'Elle Kennedy', 'Contemporary Romance'),
('The Roommate', 'Rosie Danan', 'Contemporary Romance'),
('The Intimacy Experiment', 'Rosie Danan', 'Contemporary Romance'),
('Red String Theory', 'Lauren Kung Jessen', 'Contemporary Romance'),
('Funny Story', 'Emily Henry', 'Contemporary Romance'),
('Check & Mate', 'Ali Hazelwood', 'Contemporary Romance'),
('Love Theoretically', 'Ali Hazelwood', 'Contemporary Romance'),
('The Wall of Winnipeg and Me', 'Mariana Zapata', 'New Adult Romance'),
('Kulti', 'Mariana Zapata', 'New Adult Romance'),
('From Lukov with Love', 'Mariana Zapata', 'New Adult Romance'),
('Dear Aaron', 'Mariana Zapata', 'New Adult Romance'),
('Luna and the Lie', 'Mariana Zapata', 'New Adult Romance'),
('Priest', 'Sierra Simone', 'New Adult Romance'),
('Sinner', 'Sierra Simone', 'New Adult Romance'),
('The Stopover', 'T.L. Swan', 'New Adult Romance'),
('Mr. Masters', 'T.L. Swan', 'New Adult Romance'),
('The Do-Over', 'Lynn Painter', 'New Adult Romance'),
('The Hunger Games', 'Suzanne Collins', 'Young Adult'),
('Catching Fire', 'Suzanne Collins', 'Young Adult'),
('Mockingjay', 'Suzanne Collins', 'Young Adult'),
('The Ballad of Songbirds and Snakes', 'Suzanne Collins', 'Young Adult'),
('Divergent', 'Veronica Roth', 'Young Adult'),
('Insurgent', 'Veronica Roth', 'Young Adult'),
('Allegiant', 'Veronica Roth', 'Young Adult'),
('The Maze Runner', 'James Dashner', 'Young Adult'),
('The Scorch Trials', 'James Dashner', 'Young Adult'),
('The Death Cure', 'James Dashner', 'Young Adult'),
('We Were Liars', 'E. Lockhart', 'Young Adult'),
('One of Us Is Lying', 'Karen M. McManus', 'Young Adult'),
('One of Us Is Next', 'Karen M. McManus', 'Young Adult'),
('Two Can Keep a Secret', 'Karen M. McManus', 'Young Adult'),
('The Fault in Our Stars', 'John Green', 'Young Adult'),
('Looking for Alaska', 'John Green', 'Young Adult'),
('Paper Towns', 'John Green', 'Young Adult'),
('They Both Die at the End', 'Adam Silvera', 'Young Adult'),
('The Perks of Being a Wallflower', 'Stephen Chbosky', 'Young Adult'),
('Five Feet Apart', 'Rachael Lippincott', 'Young Adult'),
('The Seven Year Slip', 'Ashley Poston', 'Mystery/Thriller'),
('The Silent Patient', 'Alex Michaelides', 'Mystery/Thriller'),
('The Maidens', 'Alex Michaelides', 'Mystery/Thriller'),
('The Guest List', 'Lucy Foley', 'Mystery/Thriller'),
('The Paris Apartment', 'Lucy Foley', 'Mystery/Thriller'),
('The Hunting Party', 'Lucy Foley', 'Mystery/Thriller'),
('Rock Paper Scissors', 'Alice Feeney', 'Mystery/Thriller'),
('Daisy Darker', 'Alice Feeney', 'Mystery/Thriller'),
('Sometimes I Lie', 'Alice Feeney', 'Mystery/Thriller'),
('The Woman in the Window', 'A.J. Finn', 'Mystery/Thriller'),
('The Girl on the Train', 'Paula Hawkins', 'Mystery/Thriller'),
('Into the Water', 'Paula Hawkins', 'Mystery/Thriller'),
('The It Girl', 'Ruth Ware', 'Mystery/Thriller'),
('The Death of Mrs. Westaway', 'Ruth Ware', 'Mystery/Thriller'),
('In a Dark Dark Wood', 'Ruth Ware', 'Mystery/Thriller'),
('The Turn of the Key', 'Ruth Ware', 'Mystery/Thriller'),
('One by One', 'Ruth Ware', 'Mystery/Thriller'),
('The Night She Disappeared', 'Lisa Jewell', 'Mystery/Thriller'),
('Then She Was Gone', 'Lisa Jewell', 'Mystery/Thriller'),
('The Family Upstairs', 'Lisa Jewell', 'Mystery/Thriller'),
('The Song of Achilles', 'Madeline Miller', 'Historical Fiction'),
('Circe', 'Madeline Miller', 'Historical Fiction'),
('All the Light We Cannot See', 'Anthony Doerr', 'Historical Fiction'),
('The Book Thief', 'Markus Zusak', 'Historical Fiction'),
('The Nightingale', 'Kristin Hannah', 'Historical Fiction'),
('The Four Winds', 'Kristin Hannah', 'Historical Fiction'),
('The Great Alone', 'Kristin Hannah', 'Historical Fiction'),
('The Women', 'Kristin Hannah', 'Historical Fiction'),
('The Invisible Life of Addie LaRue', 'V.E. Schwab', 'Historical Fiction'),
('The Midnight Library', 'Matt Haig', 'Historical Fiction'),
('Normal People', 'Sally Rooney', 'Literary Fiction'),
('Conversations with Friends', 'Sally Rooney', 'Literary Fiction'),
('Beautiful World Where Are You', 'Sally Rooney', 'Literary Fiction'),
('Where the Crawdads Sing', 'Delia Owens', 'Literary Fiction'),
('The Kite Runner', 'Khaled Hosseini', 'Literary Fiction'),
('A Thousand Splendid Suns', 'Khaled Hosseini', 'Literary Fiction'),
('And the Mountains Echoed', 'Khaled Hosseini', 'Literary Fiction'),
('The Vanishing Half', 'Brit Bennett', 'Literary Fiction'),
('The Mothers', 'Brit Bennett', 'Literary Fiction'),
('Anxious People', 'Fredrik Backman', 'Literary Fiction'),
('Just for the Summer', 'Abby Jimenez', 'Contemporary Romance'),
('Part of Your World', 'Abby Jimenez', 'Contemporary Romance'),
('Yours Truly', 'Abby Jimenez', 'Contemporary Romance'),
('The Friend Zone', 'Abby Jimenez', 'Contemporary Romance'),
('Life''s Too Short', 'Abby Jimenez', 'Contemporary Romance'),
('Love and Other Words', 'Christina Lauren', 'Contemporary Romance'),
('The Seat Filler', 'Sariah Wilson', 'Contemporary Romance'),
('The Chemistry of Love', 'Sariah Wilson', 'Contemporary Romance'),
('The Simple Wild', 'K.A. Tucker', 'Contemporary Romance'),
('Better Than the Movies', 'Lynn Painter', 'Contemporary Romance'),
('Nothing Like the Movies', 'Lynn Painter', 'Contemporary Romance'),
('Mr. Wrong Number', 'Lynn Painter', 'Contemporary Romance'),
('The Ex Talk', 'Rachel Lynn Solomon', 'Contemporary Romance'),
('Business or Pleasure', 'Rachel Lynn Solomon', 'Contemporary Romance'),
('Weather Girl', 'Rachel Lynn Solomon', 'Contemporary Romance'),
('Archer''s Voice', 'Mia Sheridan', 'Contemporary Romance'),
('Kyland', 'Mia Sheridan', 'Contemporary Romance'),
('Travis', 'Mia Sheridan', 'Contemporary Romance'),
('Meet Me at the Lake', 'Carley Fortune', 'Contemporary Romance'),
('Every Summer After', 'Carley Fortune', 'Contemporary Romance'),
('An Ember in the Ashes', 'Sabaa Tahir', 'Fantasy'),
('A Torch Against the Night', 'Sabaa Tahir', 'Fantasy'),
('A Reaper at the Gates', 'Sabaa Tahir', 'Fantasy'),
('A Sky Beyond the Storm', 'Sabaa Tahir', 'Fantasy'),
('House of Hollow', 'Krystal Sutherland', 'Fantasy'),
('The Atlas Six', 'Olivie Blake', 'Fantasy'),
('Shatter Me', 'Tahereh Mafi', 'Fantasy'),
('Caraval', 'Stephanie Garber', 'Fantasy'),
('Legendary', 'Stephanie Garber', 'Fantasy'),
('Finale', 'Stephanie Garber', 'Fantasy')
ON CONFLICT (LOWER(title), LOWER(author)) DO NOTHING;
