INSERT INTO books (title, author, genre) VALUES ('The Spanish Love Deception', 'Elena Armas', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('The Love Hypothesis', 'Ali Hazelwood', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('Beach Read', 'Emily Henry', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('Book Lovers', 'Emily Henry', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('People We Meet on Vacation', 'Emily Henry', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('Happy Place', 'Emily Henry', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('The Seven Husbands of Evelyn Hugo', 'Taylor Jenkins Reid', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('Daisy Jones & The Six', 'Taylor Jenkins Reid', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('Malibu Rising', 'Taylor Jenkins Reid', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('Carrie Soto Is Back', 'Taylor Jenkins Reid', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('The Hating Game', 'Sally Thorne', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('Red White & Royal Blue', 'Casey McQuiston', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('One Last Stop', 'Casey McQuiston', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('The Kiss Quotient', 'Helen Hoang', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('The Bride Test', 'Helen Hoang', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('The Heart Principle', 'Helen Hoang', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('From Blood and Ash', 'Jennifer L. Armentrout', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('A Kingdom of Flesh and Fire', 'Jennifer L. Armentrout', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('The Crown of Gilded Bones', 'Jennifer L. Armentrout', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('Things We Never Got Over', 'Lucy Score', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('Things We Hide from the Light', 'Lucy Score', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('The Unhoneymooners', 'Christina Lauren', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('The Soulmate Equation', 'Christina Lauren', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('The Proposal', 'Jasmine Guillory', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('The Wedding Date', 'Jasmine Guillory', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('The Time Traveler''s Wife', 'Audrey Niffenegger', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('Me Before You', 'Jojo Moyes', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('After You', 'Jojo Moyes', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('The Flatshare', 'Beth O''Leary', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('The Switch', 'Beth O''Leary', 'Romance');
INSERT INTO books (title, author, genre) VALUES ('Haunting Adeline', 'H.D. Carlton', 'Dark Romance');
INSERT INTO books (title, author, genre) VALUES ('Hunting Adeline', 'H.D. Carlton', 'Dark Romance');
INSERT INTO books (title, author, genre) VALUES ('Credence', 'Penelope Douglas', 'Dark Romance');
INSERT INTO books (title, author, genre) VALUES ('Birthday Girl', 'Penelope Douglas', 'Dark Romance');
INSERT INTO books (title, author, genre) VALUES ('Punk 57', 'Penelope Douglas', 'Dark Romance');
INSERT INTO books (title, author, genre) VALUES ('Corrupt', 'Penelope Douglas', 'Dark Romance');
INSERT INTO books (title, author, genre) VALUES ('Den of Vipers', 'K.A. Knight', 'Dark Romance');
INSERT INTO books (title, author, genre) VALUES ('Butcher & Blackbird', 'Brynne Weaver', 'Dark Romance');
INSERT INTO books (title, author, genre) VALUES ('Beneath the Stands', 'Penelope Douglas', 'Dark Romance');
INSERT INTO books (title, author, genre) VALUES ('Still Beating', 'Jennifer Hartmann', 'Dark Romance');
INSERT INTO books (title, author, genre) VALUES ('A Court of Thorns and Roses', 'Sarah J. Maas', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('A Court of Mist and Fury', 'Sarah J. Maas', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('A Court of Wings and Ruin', 'Sarah J. Maas', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('A Court of Frost and Starlight', 'Sarah J. Maas', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('A Court of Silver Flames', 'Sarah J. Maas', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Throne of Glass', 'Sarah J. Maas', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Crown of Midnight', 'Sarah J. Maas', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Heir of Fire', 'Sarah J. Maas', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Queen of Shadows', 'Sarah J. Maas', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Empire of Storms', 'Sarah J. Maas', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Tower of Dawn', 'Sarah J. Maas', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Kingdom of Ash', 'Sarah J. Maas', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Crescent City: House of Earth and Blood', 'Sarah J. Maas', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Crescent City: House of Sky and Breath', 'Sarah J. Maas', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Crescent City: House of Flame and Shadow', 'Sarah J. Maas', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Fourth Wing', 'Rebecca Yarros', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Iron Flame', 'Rebecca Yarros', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Onyx Storm', 'Rebecca Yarros', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Powerless', 'Lauren Roberts', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Reckless', 'Lauren Roberts', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Divine Rivals', 'Rebecca Ross', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Ruthless Vows', 'Rebecca Ross', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('The Cruel Prince', 'Holly Black', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('The Wicked King', 'Holly Black', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('The Queen of Nothing', 'Holly Black', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Shadow and Bone', 'Leigh Bardugo', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Siege and Storm', 'Leigh Bardugo', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Ruin and Rising', 'Leigh Bardugo', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Six of Crows', 'Leigh Bardugo', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Crooked Kingdom', 'Leigh Bardugo', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('King of Battle and Blood', 'Scarlett St. Clair', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('King of Wrath', 'Ana Huang', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('King of Pride', 'Ana Huang', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('King of Greed', 'Ana Huang', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('King of Sloth', 'Ana Huang', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Twisted Love', 'Ana Huang', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Twisted Games', 'Ana Huang', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Twisted Hate', 'Ana Huang', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('Twisted Lies', 'Ana Huang', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('A Shadow in the Ember', 'Jennifer L. Armentrout', 'Fantasy Romance');
INSERT INTO books (title, author, genre) VALUES ('The Summer I Turned Pretty', 'Jenny Han', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('It''s Not Summer Without You', 'Jenny Han', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('We''ll Always Have Summer', 'Jenny Han', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('To All the Boys I''ve Loved Before', 'Jenny Han', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('P.S. I Still Love You', 'Jenny Han', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Always and Forever Lara Jean', 'Jenny Han', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Icebreaker', 'Hannah Grace', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Wildfire', 'Hannah Grace', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Daydream', 'Hannah Grace', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('The Deal', 'Elle Kennedy', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('The Mistake', 'Elle Kennedy', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('The Score', 'Elle Kennedy', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('The Goal', 'Elle Kennedy', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('The Legacy', 'Elle Kennedy', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('The Roommate', 'Rosie Danan', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('The Intimacy Experiment', 'Rosie Danan', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Red String Theory', 'Lauren Kung Jessen', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Funny Story', 'Emily Henry', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Check & Mate', 'Ali Hazelwood', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Love Theoretically', 'Ali Hazelwood', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('The Wall of Winnipeg and Me', 'Mariana Zapata', 'New Adult Romance');
INSERT INTO books (title, author, genre) VALUES ('Kulti', 'Mariana Zapata', 'New Adult Romance');
INSERT INTO books (title, author, genre) VALUES ('From Lukov with Love', 'Mariana Zapata', 'New Adult Romance');
INSERT INTO books (title, author, genre) VALUES ('Dear Aaron', 'Mariana Zapata', 'New Adult Romance');
INSERT INTO books (title, author, genre) VALUES ('Luna and the Lie', 'Mariana Zapata', 'New Adult Romance');
INSERT INTO books (title, author, genre) VALUES ('Priest', 'Sierra Simone', 'New Adult Romance');
INSERT INTO books (title, author, genre) VALUES ('Sinner', 'Sierra Simone', 'New Adult Romance');
INSERT INTO books (title, author, genre) VALUES ('The Stopover', 'T.L. Swan', 'New Adult Romance');
INSERT INTO books (title, author, genre) VALUES ('Mr. Masters', 'T.L. Swan', 'New Adult Romance');
INSERT INTO books (title, author, genre) VALUES ('The Do-Over', 'Lynn Painter', 'New Adult Romance');
INSERT INTO books (title, author, genre) VALUES ('The Hunger Games', 'Suzanne Collins', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('Catching Fire', 'Suzanne Collins', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('Mockingjay', 'Suzanne Collins', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('The Ballad of Songbirds and Snakes', 'Suzanne Collins', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('Divergent', 'Veronica Roth', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('Insurgent', 'Veronica Roth', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('Allegiant', 'Veronica Roth', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('The Maze Runner', 'James Dashner', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('The Scorch Trials', 'James Dashner', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('The Death Cure', 'James Dashner', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('We Were Liars', 'E. Lockhart', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('One of Us Is Lying', 'Karen M. McManus', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('One of Us Is Next', 'Karen M. McManus', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('Two Can Keep a Secret', 'Karen M. McManus', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('The Fault in Our Stars', 'John Green', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('Looking for Alaska', 'John Green', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('Paper Towns', 'John Green', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('They Both Die at the End', 'Adam Silvera', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('The Perks of Being a Wallflower', 'Stephen Chbosky', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('Five Feet Apart', 'Rachael Lippincott', 'Young Adult');
INSERT INTO books (title, author, genre) VALUES ('The Seven Year Slip', 'Ashley Poston', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('The Silent Patient', 'Alex Michaelides', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('The Maidens', 'Alex Michaelides', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('The Guest List', 'Lucy Foley', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('The Paris Apartment', 'Lucy Foley', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('The Hunting Party', 'Lucy Foley', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('Rock Paper Scissors', 'Alice Feeney', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('Daisy Darker', 'Alice Feeney', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('Sometimes I Lie', 'Alice Feeney', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('The Woman in the Window', 'A.J. Finn', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('The Girl on the Train', 'Paula Hawkins', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('Into the Water', 'Paula Hawkins', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('The It Girl', 'Ruth Ware', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('The Death of Mrs. Westaway', 'Ruth Ware', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('In a Dark Dark Wood', 'Ruth Ware', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('The Turn of the Key', 'Ruth Ware', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('One by One', 'Ruth Ware', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('The Night She Disappeared', 'Lisa Jewell', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('Then She Was Gone', 'Lisa Jewell', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('The Family Upstairs', 'Lisa Jewell', 'Mystery/Thriller');
INSERT INTO books (title, author, genre) VALUES ('The Song of Achilles', 'Madeline Miller', 'Historical Fiction');
INSERT INTO books (title, author, genre) VALUES ('Circe', 'Madeline Miller', 'Historical Fiction');
INSERT INTO books (title, author, genre) VALUES ('All the Light We Cannot See', 'Anthony Doerr', 'Historical Fiction');
INSERT INTO books (title, author, genre) VALUES ('The Book Thief', 'Markus Zusak', 'Historical Fiction');
INSERT INTO books (title, author, genre) VALUES ('The Nightingale', 'Kristin Hannah', 'Historical Fiction');
INSERT INTO books (title, author, genre) VALUES ('The Four Winds', 'Kristin Hannah', 'Historical Fiction');
INSERT INTO books (title, author, genre) VALUES ('The Great Alone', 'Kristin Hannah', 'Historical Fiction');
INSERT INTO books (title, author, genre) VALUES ('The Women', 'Kristin Hannah', 'Historical Fiction');
INSERT INTO books (title, author, genre) VALUES ('The Invisible Life of Addie LaRue', 'V.E. Schwab', 'Historical Fiction');
INSERT INTO books (title, author, genre) VALUES ('The Midnight Library', 'Matt Haig', 'Historical Fiction');
INSERT INTO books (title, author, genre) VALUES ('Normal People', 'Sally Rooney', 'Literary Fiction');
INSERT INTO books (title, author, genre) VALUES ('Conversations with Friends', 'Sally Rooney', 'Literary Fiction');
INSERT INTO books (title, author, genre) VALUES ('Beautiful World Where Are You', 'Sally Rooney', 'Literary Fiction');
INSERT INTO books (title, author, genre) VALUES ('Where the Crawdads Sing', 'Delia Owens', 'Literary Fiction');
INSERT INTO books (title, author, genre) VALUES ('The Kite Runner', 'Khaled Hosseini', 'Literary Fiction');
INSERT INTO books (title, author, genre) VALUES ('A Thousand Splendid Suns', 'Khaled Hosseini', 'Literary Fiction');
INSERT INTO books (title, author, genre) VALUES ('And the Mountains Echoed', 'Khaled Hosseini', 'Literary Fiction');
INSERT INTO books (title, author, genre) VALUES ('The Vanishing Half', 'Brit Bennett', 'Literary Fiction');
INSERT INTO books (title, author, genre) VALUES ('The Mothers', 'Brit Bennett', 'Literary Fiction');
INSERT INTO books (title, author, genre) VALUES ('Anxious People', 'Fredrik Backman', 'Literary Fiction');
INSERT INTO books (title, author, genre) VALUES ('Just for the Summer', 'Abby Jimenez', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Part of Your World', 'Abby Jimenez', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Yours Truly', 'Abby Jimenez', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('The Friend Zone', 'Abby Jimenez', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Life''s Too Short', 'Abby Jimenez', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Love and Other Words', 'Christina Lauren', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('The Seat Filler', 'Sariah Wilson', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('The Chemistry of Love', 'Sariah Wilson', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('The Simple Wild', 'K.A. Tucker', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Better Than the Movies', 'Lynn Painter', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Nothing Like the Movies', 'Lynn Painter', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Mr. Wrong Number', 'Lynn Painter', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('The Ex Talk', 'Rachel Lynn Solomon', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Business or Pleasure', 'Rachel Lynn Solomon', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Weather Girl', 'Rachel Lynn Solomon', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Archer''s Voice', 'Mia Sheridan', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Kyland', 'Mia Sheridan', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Travis', 'Mia Sheridan', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Meet Me at the Lake', 'Carley Fortune', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('Every Summer After', 'Carley Fortune', 'Contemporary Romance');
INSERT INTO books (title, author, genre) VALUES ('An Ember in the Ashes', 'Sabaa Tahir', 'Fantasy');
INSERT INTO books (title, author, genre) VALUES ('A Torch Against the Night', 'Sabaa Tahir', 'Fantasy');
INSERT INTO books (title, author, genre) VALUES ('A Reaper at the Gates', 'Sabaa Tahir', 'Fantasy');
INSERT INTO books (title, author, genre) VALUES ('A Sky Beyond the Storm', 'Sabaa Tahir', 'Fantasy');
INSERT INTO books (title, author, genre) VALUES ('House of Hollow', 'Krystal Sutherland', 'Fantasy');
INSERT INTO books (title, author, genre) VALUES ('The Atlas Six', 'Olivie Blake', 'Fantasy');
INSERT INTO books (title, author, genre) VALUES ('Shatter Me', 'Tahereh Mafi', 'Fantasy');
INSERT INTO books (title, author, genre) VALUES ('Caraval', 'Stephanie Garber', 'Fantasy');
INSERT INTO books (title, author, genre) VALUES ('Legendary', 'Stephanie Garber', 'Fantasy');
INSERT INTO books (title, author, genre) VALUES ('Finale', 'Stephanie Garber', 'Fantasy');
