-- Update books table with blurbs from CSV
UPDATE books SET description = 'Catalina needs a date to her sister''s wedding in Spain, and her annoying coworker Aaron offers to be her fake boyfriend for the trip.' WHERE LOWER(title) = 'the spanish love deception' AND LOWER(author) = 'elena armas';
UPDATE books SET description = 'A third-year PhD candidate accidentally kisses a professor and convinces him to be her fake boyfriend to prove a hypothesis about relationships.' WHERE LOWER(title) = 'the love hypothesis' AND LOWER(author) = 'ali hazelwood';
UPDATE books SET description = 'Two writers with opposite genres spend a summer next to each other and challenge themselves to write in each other''s styles while falling in love.' WHERE LOWER(title) = 'beach read' AND LOWER(author) = 'emily henry';
UPDATE books SET description = 'A literary agent who always plays the supporting character in life finally gets her own love story when she keeps running into the same grumpy editor in a small town.' WHERE LOWER(title) = 'book lovers' AND LOWER(author) = 'emily henry';
UPDATE books SET description = 'Two best friends who take a summer vacation together every year haven''t spoken in two years, but agree to one more trip to fix their friendship.' WHERE LOWER(title) = 'people we meet on vacation' AND LOWER(author) = 'emily henry';
UPDATE books SET description = 'A couple who broke up months ago must pretend they''re still together during a friend group vacation at their favorite cottage.' WHERE LOWER(title) = 'happy place' AND LOWER(author) = 'emily henry';
UPDATE books SET description = 'Aging Hollywood icon Evelyn Hugo finally tells the story of her scandalous life and her seven marriages to an unknown journalist.' WHERE LOWER(title) = 'the seven husbands of evelyn hugo' AND LOWER(author) = 'taylor jenkins reid';
UPDATE books SET description = 'An oral history of a fictional 1970s rock band''s rise to fame and dramatic implosion, centering on the tempestuous relationship between two lead singers.' WHERE LOWER(title) = 'daisy jones & the six' AND LOWER(author) = 'taylor jenkins reid';
UPDATE books SET description = 'The four famous Riva siblings throw an epic party in Malibu that ends in disaster, while flashbacks reveal their family''s complicated history.' WHERE LOWER(title) = 'malibu rising' AND LOWER(author) = 'taylor jenkins reid';
UPDATE books SET description = 'A retired tennis champion makes a comeback at age 37 to reclaim her record, navigating fame, family, and a new relationship.' WHERE LOWER(title) = 'carrie soto is back' AND LOWER(author) = 'taylor jenkins reid';
